---
repos:
    - repo: git://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3.8

    - repo: git://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort

    - repo: git://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy

    - repo: git://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.10
      hooks:
          - id: remove-crlf
          - id: remove-tabs
